### ISSUE TITLE
Practica de Test Case

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-test-case-entrevista-mitte#2]
[Practica de Test Case MiTTE.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-test-case-entrevista-mitte/files/7340487/Practica.de.Test.Case.MiTTE.pdf)

**Comment by Edwin-1012** [comment]
20 % Cumple con todos los datos requeridos y la rubrica.

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado.
